name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@main
      with:
        node-version: 18.x
    - name: Create Firebase config file
      run: |
        echo "const firebaseConfig = {" > src/config/firebaseConfig.js
        echo "  apiKey: '$FIREBASE_API_KEY'," >> src/config/firebaseConfig.js
        echo "  authDomain: '$FIREBASE_AUTH_DOMAIN'," >> src/config/firebaseConfig.js
        echo "  projectId: '$FIREBASE_PROJECT_ID'," >> src/config/firebaseConfig.js
        echo "  storageBucket: '$FIREBASE_STORAGE_BUCKET'," >> src/config/firebaseConfig.js
        echo "  messagingSenderId: '$FIREBASE_MESSAGING_SENDER_ID'," >> src/config/firebaseConfig.js
        echo "  appId: '$FIREBASE_APP_ID'," >> src/config/firebaseConfig.js
        echo "  measurementId: '$FIREBASE_MEASUREMENT_ID'," >> src/config/firebaseConfig.js
        echo "};" >> src/config/firebaseConfig.js
        echo "export default firebaseConfig;" >> src/config/firebaseConfig.js
      env:
        FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
        FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
        FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
        FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
        FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
        FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
        FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
    - name: Display updated Firebase config
      run: cat src/firebaseConfig.js
    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

